### ISSUE TITLE
Qovluq və fayl strukturu

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [hikmatrajabzade/PragmatechFoundationProject#1]
### <p align="center">Qovluq və fayl strukturu bu şəkildə olmalıdır.</p>
![Qovluq və fayl strukturu](https://user-images.githubusercontent.com/86655646/143594569-774a940f-590c-4f40-939c-161acc185d63.png)

**[Bu](https://github.com/PragmatechEducation/FoundationStudent)** və **[bu](https://medium.com/@nmayurashok/file-and-folder-structure-for-web-development-8c5c83810a5)** qaynaqlardakı kimi olmalıdır hər şey. Qaynaqları yaxşıca analiz edin və tətbiq etməyə çalışın.

**Comment by hikmatrajabzade** [comment]
Təşəkkür edirəm. İndi mən hal hazırki işlərimi works faylına atmalıyam ya ProjectFrontEnd?

**Comment by isbendiyarovanezrin** [comment]
"Works" qovluğunun içində **[bu](https://github.com/PragmatechEducation/FoundationStudent/tree/main/Works)** linkdəki kimi qovluqlar yaradıb uyğun qovluğa işlərinizi ata bilərsiniz.

**Comment by hikmatrajabzade** [comment]
Təşəkkürlər həll olundu. Yenə göz ata bilərsiniz

**Comment by isbendiyarovanezrin** [comment]
"Works" qovluğunun içi mən dediyim kimi olsa daha yaxşı olardı, qalan əla.✌

**Comment by hikmatrajabzade** [comment]
Onu da düzəlttim bu səfər okey :)
